### PR TITLE
Try to fix android ime crash

### LINKED ISSUE #714: IPv4Box does not work on Android
Hi! I downloaded and installed (com.irihitech.Ursa-Signed.apk) on Android latest release 1.11.1.
When checking the IPv4Box control, my application crashes. What should I do?

### PR DESCRIPTION
**Pull request by rabbitism**
implement two selection related features to avoid app crash. 
Closes #714

### CODE REVIEW

File: src/Ursa/Controls/IPv4Box/IPv4Box.cs [hunk 1]
```diff
@@ -283,11 +283,13 @@ protected override void OnPointerPressed(PointerPressedEventArgs e)
             {
                 if (e.ClickCount == 1)
                 {
-                    _imClient.SetPresenter(presenter);
-                    presenter.ShowCaret();
+                    _imClient.ShowInputPanel();
```
Comment (maxkatz6) [inline src/Ursa/Controls/IPv4Box/IPv4Box.cs:286]: `ShowInputPanel` is going to be removed in 12.0
But there will be another alternative for 11.3.x
https://github.com/AvaloniaUI/Avalonia/pull/19225

Comment (rabbitism) [reply src/Ursa/Controls/IPv4Box/IPv4Box.cs:286]: It's not working well here anyway. Thanks.
